# Review Story Workflow
name: code-review
description: "Perform an ADVERSARIAL Senior Developer code review that finds 3-10 specific problems in every story. Challenges everything: code quality, test coverage, architecture compliance, security, performance. NEVER accepts `looks good` - must find minimum issues and can auto-fix with user approval."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/.bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/4-implementation/code-review"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"
template: false

<template-output>
**🔥 CODE REVIEW FINDINGS, Riddler!**

**Story:** 1-1-cmake-project-structure-dependencies.md
**Git vs Story Discrepancies:** 2 found (Files modified in git but not in story: `src/server/websocket_session.{cpp,hpp}`)
**Issues Found:** 1 High, 1 Medium, 2 Low

## 🔴 CRITICAL ISSUES
- **[High] Missing Compiler Warnings in Common Library**: `poker_common` is defined as `STATIC` in `src/common/CMakeLists.txt` but does NOT link `project_warnings` or `project_options` in the root `CMakeLists.txt`. The comment in root CMake incorrectly states it's an `INTERFACE` library. This means common code (protocol, rules) is NOT being checked with strict warnings.

## 🟡 MEDIUM ISSUES
- **[Medium] Test Architecture Violation**: `tests/CMakeLists.txt` compiles `../src/server/websocket_server.cpp` directly into the test executable. This duplicates compilation and hides visibility issues. Server logic should be in a library (e.g., `poker_server_lib`) that both the executable and tests link to.

## 🟢 LOW ISSUES
- **[Low] Hardcoded Port**: `src/server/main.cpp` has hardcoded `port = 8080`. Should be configurable or at least a constant in a settings header.
- **[Low] Documentation Mismatch**: Story 1-1 claims `poker_common` is an `INTERFACE` library, but it is actually `STATIC`.

</template-output>

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: SELECTIVE LOAD - only load the specific epic needed for this story review
input_file_patterns:
  architecture:
    description: "System architecture for review context"
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/*.md"
    load_strategy: "FULL_LOAD"
  ux_design:
    description: "UX design specification (if UI review)"
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/*.md"
    load_strategy: "FULL_LOAD"
  epics:
    description: "Epic containing story being reviewed"
    whole: "{output_folder}/*epic*.md"
    sharded_index: "{output_folder}/*epic*/index.md"
    sharded_single: "{output_folder}/*epic*/epic-{{epic_num}}.md"
    load_strategy: "SELECTIVE_LOAD"
  document_project:
    description: "Brownfield project documentation (optional)"
    sharded: "{output_folder}/index.md"
    load_strategy: "INDEX_GUIDED"

standalone: true